export const graphicDesign = [
  {
    title: 'Fan Into Flame Flyer 1',
    description: "Description",
      image: '/GraphicDesign/Flyer_1 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 0,
  },
  {
    title: 'Fan Into Flame Flyer 2',
    description: "Description",
      image: '/GraphicDesign/Flyer_2 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 1,
  },
  {
    title: 'Fan Into Flame Flyer 3',
    description: "Description",
      image: '/GraphicDesign/Flyer_3 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 2,
  },
  {
    title: 'Fan Into Flame Flyer 4',
    description: "Description",
      image: '/GraphicDesign/Flyer_4 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 3,
  },{
    title: 'Fan Into Flame Flyer 5',
    description: "Description",
      image: '/GraphicDesign/Flyer_5 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 4,
  },
  {
    title: 'Fan Into Flame Flyer 6',
    description: "Description",
      image: '/GraphicDesign/Flyer_6 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 5,
  },
  {
    title: 'Country Sunrise',
    description: "Description",
      image: '/GraphicDesign/InstaCountrySunrise copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 6,
  }, {
    title: 'Person By The Ocean',
    description: "Description",
      image: '/GraphicDesign/InstaOceanPersonpng copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 7,
  }, {
    title: 'Lake Sunrise',
    description: "Description",
      image: '/GraphicDesign/InstaSunriseLake copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 8,
  },{
    title: 'Hill Sunset',
    description: "Description",
      image: '/GraphicDesign/InstaSunsetFarHills copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 9,
  }, {
    title: 'UCO Bottle',
    description: "Description",
      image: '/GraphicDesign/InstaUCOBottle copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 10,
  }, {
    title: 'Postcard Back',
    description: "Description",
      image: '/GraphicDesign/Postcard_Back copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 11,
  }, {
    title: 'Postcard Option 1',
    description: "Description",
      image: '/GraphicDesign/Postcard_Op1_revise copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 12,
  }, {
    title: 'Postcard Option 2',
    description: "Description",
      image: '/GraphicDesign/Postcard_Op2 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 13,
  }, {
    title: 'Postcard Option 3',
    description: "Description",
      image: '/GraphicDesign/Postcard_Op3_Revise copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 14,
  }, {
    title: 'Postcard Option 4',
    description: "Description",
      image: '/GraphicDesign/Postcard_Op4 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 15,
  }, {
    title: 'Postcard Option 5',
    description: "Description",
      image: '/GraphicDesign/Postcard_Op5_Revise copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 16,
  }, {
    title: 'Postcard Option 6',
    description: "Description",
      image: '/GraphicDesign/Postcard_Op6 copy.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'image',
    id: 17,
  },
  {
    title: 'Fan Into Flames Video',
    description: "Description",
      image: '/GraphicDesign/KineticFIFpost_1 copy.mp4',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    type: 'video',
    id: 18,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];